name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v'

jobs:
  build:
    name: Build for Windows and Linux
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Build for Linux and Windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x # Specify the .NET version you use

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet publish --configuration Release --self-contained --output ./out

      - name: Archive Build
        run: |
            if [ ${{ matrix.os }} == 'windows-latest' ]; then
            powershell -Command "Compress-Archive -Path ./out/* -DestinationPath KeaCore-windows.zip"
            else
            cd out && zip -r ../KeaCore-linux.zip * && cd ..
            fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeaCore-${{ matrix.os == 'ubuntu-latest' && 'linux' || 'windows' }}
          path: KeaCore-${{ matrix.os == 'ubuntu-latest' && 'linux' || 'windows' }}.zip

  release:
    name: Create Release and Upload Artifacts
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: KeaCore-linux.zip
          path: ./

      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: KeaCore-windows.zip
          path: ./

      - name: Create Release
        uses: softprops/action-gh-release@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            KeaCore-linux.zip
            KeaCore-windows.zip
